chore: helm test

diff --git a/charts/telicent-core/charts/search-projector/templates/tests/test-connection.yaml b/charts/telicent-core/charts/search-projector/templates/tests/test-connection.yaml
--- a/charts/telicent-core/charts/search-projector/templates/tests/test-connection.yaml
+++ b/charts/telicent-core/charts/search-projector/templates/tests/test-connection.yaml
@@ -1,20 +1,28 @@
+{{- /*
+Copyright (C) 2025 Telicent Limited
+*/}}
 apiVersion: v1
 kind: Pod
+
 metadata:
   name: {{ include "search-projector.fullname" . }}-test-connection
+  namespace: {{ .Release.Namespace }}
   labels:
     {{- include "search-projector.labels" . | nindent 4 }}
   annotations:
     "helm.sh/hook": test
+    sidecar.istio.io/inject: "false"
 
 spec:
-  restartPolicy: Never
+  restartPolicy: Never # do not restart automatically, regardless of the exit status
   containers:
     - name: istio-403
-      image: alpine/curl:8.1.14
+      image: alpine/curl:8.14.1
       imagePullPolicy: IfNotPresent
       command: [ "/bin/sh", "-c" ]
       args:
         - |
-          output="$(curl http://{{ include "search-projector.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.metrics.service.port }})"; \
-          echo "$output" | grep "403"
+          sleep 15;
+          output="$(curl -sS --retry 10 --retry-delay 10 --retry-connrefused http://{{ include "search-projector.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.metrics.service.port }})";
+          echo "attempting an unauthorized request... $output";
+          echo "$output" | grep "access denied" || ( echo "error: expected 403, RBAC access denied" && exit 1 );
